name: prom-metrics-linter
on:
  release:
    types:
      - published
env:
  IMAGE_NAME: quay.io/kubevirt/prom-metrics-linter
  BUILD_PLATFORMS: linux/amd64,linux/arm64,linux/s390x

jobs:
  build:
    name: Upload prom-metrics-linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.0.0

      - name: Login to quay.io
        run: docker login -u="${{ secrets.QUAY_USER }}" -p="${{ secrets.QUAY_PASSWORD }}" quay.io

      - name: Build and push the Docker image
        uses: docker/build-push-action@v5.3.0
        with:
          context: test/metrics/prom-metrics-linter
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ github.ref_name }}
          file: test/metrics/prom-metrics-linter/Dockerfile
          platforms: ${{ env.BUILD_PLATFORMS }}
